#include "ui.hpp"
extern "C" {void layout_home(Clay_RenderCommandArray& rc) {
Clay_BeginLayout();CLAY({.id=CLAY_ID("body"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)},.layoutDirection=CLAY_TOP_TO_BOTTOM},.backgroundColor=theme::background_color}){
  CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT)},.padding=theme::gpad,.childGap=10,.childAlignment={.x=CLAY_ALIGN_X_CENTER,.y=CLAY_ALIGN_Y_CENTER},.layoutDirection=CLAY_LEFT_TO_RIGHT}}){
    CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2)}},.backgroundColor=theme::command_background}){
      CLAY({.id=CLAY_ID("btn_options"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={255,255,255,255},.image={.imageData=btns+BTI_OPT,.sourceDimensions=theme::IMG_SCALE}}){}}CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::SAFETY_MARGIN),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={0,0,0,0}}){}CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2)}},.backgroundColor=theme::command_background}){
      CLAY({.id=CLAY_ID("btn_parent"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={255,255,255,255},.image={.imageData=btns+BTI_UP,.sourceDimensions=theme::IMG_SCALE}}){}}CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(100)},.padding=theme::gpad,.childGap=10,.layoutDirection=CLAY_LEFT_TO_RIGHT},.backgroundColor=theme::text_field_bg_color}){
      CLAY_TEXT(
        to_clay_string(tts_fill_final_buffer())
      , get_font_config());}CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2)}},.backgroundColor=theme::command_background}){
      CLAY({.id=CLAY_ID("btn_backspace"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={255,255,255,255},.image={.imageData=btns+BTI_BACKSPACE,.sourceDimensions=theme::IMG_SCALE}}){}}CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2)}},.backgroundColor=theme::command_background}){
      CLAY({.id=CLAY_ID("btn_clear"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={255,255,255,255},.image={.imageData=btns+BTI_CLEAR,.sourceDimensions=theme::IMG_SCALE}}){}}CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::SAFETY_MARGIN),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={0,0,0,0}}){}CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT - theme::gpad*2)}},.backgroundColor=theme::command_background}){
      CLAY({.id=CLAY_ID("btn_play"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={255,255,255,255},.image={.imageData=btns+BTI_PLAY,.sourceDimensions=theme::IMG_SCALE}}){}}}CLAY({.id=CLAY_ID("actions"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=theme::BAR_HEIGHT}},.backgroundColor={0,0,0,0}}){}CLAY({.id=CLAY_ID("content"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={0,0,0,0}}){}}rc = Clay_EndLayout();}}