#include "ui.hpp"
extern "C" {void layout_options(Clay_RenderCommandArray& rc) {
Clay_BeginLayout();CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)},.layoutDirection=CLAY_TOP_TO_BOTTOM},.backgroundColor=theme::background_color}){
  CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT)},.layoutDirection=CLAY_LEFT_TO_RIGHT},.backgroundColor=theme::command_background}){
    CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(50),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={0,0,0,0}}){}CLAY({.id=CLAY_ID("btn_back"),.layout={.sizing={.width=CLAY_SIZING_FIXED(theme::BAR_HEIGHT),.height=CLAY_SIZING_FIXED(theme::BAR_HEIGHT)}},.backgroundColor={255,255,255,255},.image={.imageData=btns+BTI_BACKSPACE,.sourceDimensions=theme::IMG_SCALE}}){}}CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)},.layoutDirection=CLAY_LEFT_TO_RIGHT}}){
    CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={0,0,0,0}}){}CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(800),.height=CLAY_SIZING_GROW(0)},.layoutDirection=CLAY_TOP_TO_BOTTOM},.scroll={.vertical=true}}){

    CLAY({.id=CLAY_ID("load_board"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(150)},.padding={theme::gpad,theme::gpad,theme::gpad,theme::gpad},.childAlignment={.y=CLAY_ALIGN_Y_CENTER}},.border={.color={150,150,150,255},.width={.left=2,.right=2,.bottom=2}}}){
      CLAY_TEXT( CLAY_STRING("Load new board") , get_font_config());}CLAY({.id=CLAY_ID("default_board"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(150)},.padding={theme::gpad,theme::gpad,theme::gpad,theme::gpad},.childAlignment={.y=CLAY_ALIGN_Y_CENTER}},.border={.color={150,150,150,255},.width={.left=2,.right=2,.bottom=2}}}){
      CLAY_TEXT( CLAY_STRING("Set default board") , get_font_config());}CLAY({.id=CLAY_ID("background"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(150)},.padding={theme::gpad,theme::gpad,theme::gpad,theme::gpad},.childAlignment={.y=CLAY_ALIGN_Y_CENTER}},.border={.color={150,150,150,255},.width={.left=2,.right=2,.bottom=2}}}){
      CLAY_TEXT( CLAY_STRING("Change background color") , get_font_config());CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)},.childAlignment={.x=CLAY_ALIGN_X_RIGHT,.y=CLAY_ALIGN_Y_CENTER}}}){
        CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(50),.height=CLAY_SIZING_FIXED(50)}},.backgroundColor=theme::background_color,.border={.color={0,0,0,255},.width={2,2,2,2}}}){}}}CLAY({.id=CLAY_ID("button"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(150)},.padding={theme::gpad,theme::gpad,theme::gpad,theme::gpad},.childAlignment={.y=CLAY_ALIGN_Y_CENTER}},.border={.color={150,150,150,255},.width={.left=2,.right=2,.bottom=2}}}){
      CLAY_TEXT( CLAY_STRING("Change button color") , get_font_config());CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)},.childAlignment={.x=CLAY_ALIGN_X_RIGHT,.y=CLAY_ALIGN_Y_CENTER}}}){
        CLAY({.layout={.sizing={.width=CLAY_SIZING_FIXED(50),.height=CLAY_SIZING_FIXED(50)}},.backgroundColor=theme::command_background}){}}}CLAY({.id=CLAY_ID("font"),.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_FIXED(150)},.padding={theme::gpad,theme::gpad,theme::gpad,theme::gpad},.childAlignment={.y=CLAY_ALIGN_Y_CENTER}},.border={.color={150,150,150,255},.width={.left=2,.right=2,.bottom=2}}}){
      CLAY_TEXT( CLAY_STRING("Change font") , get_font_config());}}CLAY({.layout={.sizing={.width=CLAY_SIZING_GROW(0),.height=CLAY_SIZING_GROW(0)}},.backgroundColor={0,0,0,0}}){}}};;rc = Clay_EndLayout();}}